### ISSUE TITLE
Large datasets

### ISSUE THREAD

**Issue by ftayyab** [koopjs/koop#345]
Hi,

Can someone advice on how to incorporate a GeoJSON source which has large number of features. I have got it working for small datasets and features appear find both in ArcGIS Pro and Online however for large datasets it timesout. i am also using the builtin cache however that doesnt seem to help. Also can someone clarify how to implement pass through vs cached data flow.

Thanks

**Comment by apfister** [comment]
hi @ftayyab. any chance you have access to Azure and the ability to run an Azure Redis Cache? I've implemented this for larger geojson files and it's been pretty seamless. Take a look here for my implementation, https://github.com/apfister/sdmx-koop-provider#setting-up-the-redis-cache. 

here is the azure doc on how to get started if you need it, https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-nodejs-get-started.

**Comment by ftayyab** [comment]
Hi Adam,

Appreciate the reply. I have access to AWS and can make use of that. However I will look into your example. I am still not sure as to why using the internal memory cache is still so slow. I can have feature upto 60000 to 100000 in GeoJSON files.

**Comment by apfister** [comment]
are you running it on a machine that has enough resources to handle that load?

**Comment by ftayyab** [comment]
I am running locally at the moment which is on a powerful machine and at the moment I am having point data. Polygon dataset from GeoJSON is much slower anyway. Just trying to figure out how to speed up. It seems there is no pagination in place.

Also difference between Cached vs. Pass-Through Providers is not very clear in terms of how to implement it.

**Comment by ftayyab** [comment]
Yes have read through the documentation, maybe I am missing something. In theory it makes sense but I wasnt too sure how to enable which mode. From my understanding (correct me if I am wrong), does koop not perform periodic caching of data from source or is the caching only invoked on an api request. It would actually help to know and I think the documentation is lacking some important bits, especially the use case where we have to deal with large datasets.

**Comment by rgwozdz** [comment]
@ftayyab - you are right that you need to implement your provider as what we call "pass-through".  Here's the difference between cached vs pass-through:

**cached:**  fetches ALL data from the remote source at once, then lets Koop filter data down to the subset requested by the client
**pass-through:** transforms incoming GeoServices API request parameters to their analog for the remote API, and uses those request parameters to fetch *only* the specific data needed by the request

Here's an example.  Suppose the ArcGIS Pro request includes the following query params:
```
where=type=park
resultRecordCount=100
```
In a pass-through provider, you would have to transform some or all of these query parameters to their analogs on your targeted remote API.  Then, use them in the request to the remote API so that Koop only fetches 100 records of type "park".

If you have a very large number of features, you need to implement the pass-through pattern in order to have decent performance.  Depending on the remote API, there may or may not be analogs for every GeoServices API query param.  If you are using S3, you should look into extending the S3 Select provider, as you can use it to limit the data fetched from large s3 files. https://github.com/koopjs/koop-provider-s3-select

**Comment by rgwozdz** [comment]
@ftayyab data is only added to cache after an API request.  No periodic scraping occurs.

**Comment by ftayyab** [comment]
Thanks for the explanation. I will certainly look at S3 Select. I assume then there is no way to retrieve all data in one go and thats where vector tiles might be preferred option.

**Comment by rgwozdz** [comment]
You can try to get all the data in one go - I assume that is what you are doing now, but that is what is likelycreating your performance bottleneck.  You need to reduce the amount of data you are moving from the remote source/API -> Koop -> client
Pre-built vector tiles on S3 would definitely solve that problem; but if you wanted Koop to build the tiles on demand, you would have a similar issue and need to only fetch the data needed for a given tile request.

**Comment by ftayyab** [comment]
yes correct. I think that is what I am doing at the moment.

`Model.prototype.getData = function (req,callback){
    let s3 = new AWS.S3();
    s3.getObject({
        Bucket : "***", Key : "***.json"
    }, (err,data)=>{
        if (err){
            return callback(err, null);
        }
        else
        {
            //console.log(data.Body.toString());
            let geoJSON = JSON.parse(data.Body.toString());
            
            geoJSON.metadata = {
                name: 'Refinery',
                idField: 'OBJECTID'
            }

            for (let i=0;i<geoJSON.features.length;i++){
                geoJSON.features[i].properties.OBJECTID=transformId(i);
            }
            const geojson = translate(geoJSON)
            const options = {
                ttl: 1000 // The TTL option is measured in seconds, it will be used to set the `expires` field in the catalog entry
            }

            cache.insert('refinery', geojson, options, err => {
                // This function will call back with an error if there is already data in the cache using the same key
                if (err){
                    console.log(err);
                }
            })
            
            const out_options= {}
            cache.retrieve('refinery', out_options, (err, geojson) => {
                callback(null,geojson);
            });`

**Comment by rgwozdz** [comment]
Yes, ok, I would guess that your file on S3 is to big to fetch from S3 before the timeout.  If your file is very large, you'll need to figure out a way pull small chunks of data.  Unfortunately the S3 Select provider doesn't support paging (yet). Neither does S3 Select for that matter - its API is only equipped with a simple `LIMIT` parameter.
The alternative is to use AWS Athena on your S3 file and create a new Koop Athena provider which would translate GeoService API parameter to their equivalents in the Athena API.  This provider is on our roadmap, but not yet underway.

BTW, you don't need to do the `cache` operations inside your provider;  Koop will handle that internally, so long as you have a top level property `ttl` on the GeoJSON sent to your callback:

```
geojson.ttl = 1000
callback(geojson)
// Koop will then add this geojson to the cache for you
```
