### ISSUE TITLE
esri-leaflet fitbounds

### ISSUE THREAD

**Issue by mapsgeek** [koopjs/koop#348]
as for the example here

https://esri.github.io/esri-leaflet/examples/zooming-to-all-features-1.html

i was expecting the same behavior when i replace the feature service but you get an error because the `latlngbounds` is actually null with features coming from koop
meanwhile for services in the example coming from arcgis online is like this

![image](https://user-images.githubusercontent.com/10188264/60114385-0822a700-9774-11e9-9b5b-3e4670cf9035.png)

**Comment by mapsgeek** [comment]
is there any input on this please ?

**Comment by mapsgeek** [comment]
@rgwozdz  any input on this please ?

**Comment by rgwozdz** [comment]
Can you share your leaflet code? Specifically the code you use to add the Koop layer?

**Comment by mapsgeek** [comment]
it's just as the doc example but just replaced the url to koop
https://jsbin.com/sohojutini/edit?html,output

**Comment by rgwozdz** [comment]
Thanks @mapsgeek.  You have identified a missing route we need in FeatureServer.  I'll try to knock that out and publish a fix ASAP.

**Comment by mapsgeek** [comment]
actually if you mean that missing route
`http://koopserver.herokuapp.com/file-geojson/rest/services/country/FeatureServer/0/?f=json`
which responds with method not supported ? i tried to edit the regex related to that function but honestly i couldn't fix, anyway thank you for help i'm trying to configure a stack for my project if i can get koop working well with esri-leaflet it would be great.

**Comment by rgwozdz** [comment]
Yes, that's the one.  My guess is that since esri-leaflt gets the 400 error on that it thinks the service doesn't support ArcGIS REST API, and therefore doesn't use the f=geojson param.

**Comment by mapsgeek** [comment]
honestly i don't really understand the featureService specs as i always work with plain Geojson
but i thought that

this request esri-leaflet makes and even arcgis online i believe
https://services.arcgis.com/rOo16HdIMeOBI4Mb/arcgis/rest/services/Heritage_Trees_Portland/FeatureServer/0/?f=json

is equivalent in response as this in koop
http://koopserver.herokuapp.com/file-geojson/rest/services/country/FeatureServer/0

but the regex function was returning unsupported because it doesn't have a case where it has the parameter `?f=json` so i just added an ifelse case with a regex to bypass but found no change and wasn't too confident about what i'm doing to suggest any solutions

**Comment by rgwozdz** [comment]
@mapsgeek - I've updated the regex to handle these routes and republished FeatureServer.  If you upgrade your FeatureServer dependency to 2.19.0, it should solve the initially identified issue.

**Comment by mapsgeek** [comment]
thank you but it doesn't fix the missing bounds since esri-leaflet still request the queries with `&f=json`
while in the example it fetches with `&f=geojson` which i believe what makes leaflet able to identify the bounds, however the `400` error gone and the suspected initial request was successful, i will try to open an issue on esri-leaflet since the koop endpoint works just fine on ArcGIS online so maybe it's a client-side issue.

**Comment by rgwozdz** [comment]
@mapsgeek - this doesn't solve problem, but gets you farther; In your esri-leaflet code, set `isModern: true`

```
    var trees = L.esri.featureLayer({
      url: 'http://koopserver.herokuapp.com/file-geojson/rest/services/country/FeatureServer/0',
      isModern: true 
    }).addTo(map);
```

**Comment by mapsgeek** [comment]
i understand, however that `isModern` option now makes the library fetches as geojson but it doesn't as well solve the issue producing the same error and also causes rendering issues with the map not showing any shapes other than the very first fetched query, so if you have the map `setView` to the US for example, this is what will only get rendered on the map, i'm starting to give up on it and work with leaflet alone with plain geojson , thank you though for all your assistance

**Comment by rgwozdz** [comment]
@mapsgeek - I understand; however this is helpful for us in making upgrades to Koop.  I've identified the issue inside Koop;  it's not honoring the `returnExtentOnly` parameter and am checking into it now.

**Comment by mapsgeek** [comment]
i appreciate the work you guys doing on koop, however i understand the main goal from it is to be a bridge between data sources and ArcGIS online but i got too excited that i can actually try to use something different than the usual ' geojson or vector-tiles stack ' in open source libraries and without the need of ArcGIS online services but then got slammed at the first feature i tried to add which is zoom to layer !

**Comment by rgwozdz** [comment]
@mapsgeek - publishing a fix for this shortly.  Once published, you won't have to use the `isModern` option.

**Comment by rgwozdz** [comment]
@mapsgeek - yesterday I released v 2.19.0 of FeatureServer.  It includes support for `returnExtentOnly` which Esri-Leaflet needs for fitbounds to work properly.
